import type { Metadata } from "next";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";

// Use system fonts as fallback to avoid external Google Font fetching during build.
const systemFontClass = "font-sans"; // Tailwind default sans font stack.

export const metadata: Metadata = {
  title: "HR-Management",
  description: "Generated by create next app",
  icons: {
    icon: "/logo2 copy 2.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
        lang="en"
        className={`${systemFontClass} h-full antialiased`}
      >
      <TooltipProvider>
        <body className="min-h-full flex flex-col">{children}</body>
      </TooltipProvider>
      
    </html>
  );
}
